apiVersion: v2
name: todo-jakarta-data-chart
description: A Helm chart to deploy a WildFly todo-jakarta-data application and its Postgresql database
type: application
version: 1.0.0
dependencies:
    - name: wildfly
      repository: http://docs.wildfly.org/wildfly-charts/
      version: 2.3.2
