apiVersion: v2
name: todo-backend-chart
description: A Helm chart to deploy a WildFly todo-backend application and its Postgresql database
type: application
version: 1.0.0
appVersion: 31.0.0.Final
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.2.2
    - name: wildfly
      repository: http://docs.wildfly.org/wildfly-charts/
      version: 2.3.2