name: WildFly todo-jakarta-data Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'todo-jakarta-data/**'
      - '.github/workflows/quickstart_ci.yml'
jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: todo-jakarta-data
      TEST_PROVISIONED_SERVER: true
      TEST_OPENSHIFT: true
      MATRIX_OS: '"ubuntu-latest"'
      EXTRA_RUN_ARGS: '-DPOSTGRESQL_DATABASE=todos -DPOSTGRESQL_SERVICE_HOST=localhost -DPOSTGRESQL_SERVICE_PORT=5432 -DPOSTGRESQL_USER=todos -DPOSTGRESQL_PASSWORD=mysecretpassword -DPOSTGRESQL_DATASOURCE=ToDos'
