name: WildFly mail Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'mail/**'
      - '.github/workflows/quickstart_ci.yml'

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: mail
      TEST_PROVISIONED_SERVER: true
      TEST_OPENSHIFT: true
      MATRIX_OS: '"ubuntu-latest"'
